stages:
- test

docs:
  stage: test
  image: sphinxdoc/sphinx
  variables:
    PIP_DISABLE_PIP_VERSION_CHECK: 1
    PIP_NO_PYTHON_VERSION_WARNING: 1
    XDG_CACHE_HOME: ${CI_PROJECT_DIR}/.cache/
  script:
  - "chown -R $(id --name --user): ${XDG_CACHE_HOME}"
  - pip install pallets_sphinx_themes
  - pip install --no-deps .
  - make -C docs/ html
  artifacts:
    paths: [docs/build/html/]
    expire_in: 1 days
  cache:
    paths: [.cache/]


tests:
  stage: test
  image: circleci/python:3.7-buster
  services:
  - postgres:11-alpine
  - rabbitmq:3-alpine
  variables:
    BROKER_URL: amqp://rabbitmq
    PGHOST: postgres
    PGUSER: postgres
    PGPASSWORD: tondeuse
    # For postgres container
    POSTGRES_PASSWORD: tondeuse
    XDG_CACHE_HOME: ${CI_PROJECT_DIR}/.cache/
  script:
  - sudo chown -R $(id --user) ${XDG_CACHE_HOME}
  - python --version
  - poetry --version
  - poetry install --verbose
  - poetry run pip install dramatiq[rabbitmq,watch]  # Workaround bug in poetry 0.X
  - poetry run flake8 example.py flask_dramatiq.py tests/func/
  - poetry run ./example.py db upgrade
  - poetry run pytest -x tests/unit/
  - poetry run pytest -x tests/func/
  cache:
    paths: [.cache/]
