"""empty message

Revision ID: 7dbb2c8d56bc
Revises:
Create Date: 2019-03-06 15:30:40.010587

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7dbb2c8d56bc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jobs")
    # ### end Alembic commands ###
